server:
  port: 8082

otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: invoice-service
      service: invoice-service
      env: dev

order:
  service:
    base-url: http://localhost:8080

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer